/* بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ ﷺ InshaAllah */

export const industryTypes = [
  "Aerospace & Defense",
  "Agriculture & Forestry",
  "Automotive",
  "Banking & Financial Services",
  "Biotechnology & Life Sciences",
  "Chemicals & Materials",
  "Construction & Real Estate",
  "Consumer Packaged Goods (CPG)",
  "Education & EdTech",
  "Energy & Utilities",
  "Entertainment & Media",
  "Environmental & Waste Management",
  "Fashion & Apparel",
  "Food & Beverage",
  "Government & Public Sector",
  "Healthcare & Medical Devices",
  "Hospitality & Tourism",
  "Insurance",
  "Legal Services",
  "Logistics & Supply Chain",
  "Manufacturing",
  "Mining & Metals",
  "Nonprofit & Social Impact",
  "Pharmaceuticals",
  "Professional & Business Services",
  "Retail & E-commerce",
  "Software & Technology",
  "Telecommunications",
  "Transportation"
] as const;

export const languages = [
  "Arabic",
  "Bengali",
  "Chinese (Mandarin)",
  "Dutch",
  "English",
  "French",
  "German",
  "Greek",
  "Gujarati",
  "Hebrew",
  "Hindi",
  "Indonesian",
  "Italian",
  "Japanese",
  "Korean",
  "Marathi",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Russian",
  "Spanish",
  "Swahili",
  "Swedish",
  "Tamil",
  "Telugu",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese"
] as const;

export const nationalities = [
  "American",
  "Argentinian",
  "Australian",
  "Bangladeshi",
  "Brazilian",
  "British",
  "Canadian",
  "Chinese",
  "Colombian",
  "Dutch",
  "Egyptian",
  "Emirati",
  "Filipino",
  "French",
  "German",
  "Greek",
  "Indian",
  "Indonesian",
  "Irish",
  "Italian",
  "Japanese",
  "Kenyan",
  "Korean",
  "Mexican",
  "Nigerian",
  "Pakistani",
  "Polish",
  "Portuguese",
  "Russian",
  "Saudi",
  "South African",
  "Spanish",
  "Swedish",
  "Swiss",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Vietnamese"
] as const;

export const religions = [
  "Baha'i",
  "Buddhism",
  "Christianity",
  "Confucianism",
  "Druze",
  "Hinduism",
  "Islam",
  "Jainism",
  "Judaism",
  "Shinto",
  "Sikhism",
  "Taoism",
  "Zoroastrianism",
  "Atheism",
  "Agnosticism",
  "Secular / Non-religious",
  "Other"
] as const;

export const interest = [
    "finance",
    "personal_finance",
    "investing",
    "trading",
    "cryptocurrency",
    "stock_market",
    "real_estate",
    "entrepreneurship",
    "startups",
    "marketing",
    "economics",

    // Religion & Spirituality
    "islamic_content",
    "quran_studies",
    "hadith",
    "christianity",
    "hinduism",
    "buddhism",
    "spirituality",
    "meditation",

    // Entertainment
    "movies",
    "tv_shows",
    "anime",
    "kdrama",
    "bollywood",
    "hollywood",
    "celebrity_news",
    "comedy",
    "theatre",

    // Music
    "music",
    "hip_hop",
    "pop_music",
    "rock_music",
    "classical_music",
    "edm",
    "kpop",
    "islamic_nasheed",
    "live_concerts",

    // Sports & Fitness
    "sports",
    "football_soccer",
    "cricket",
    "basketball",
    "tennis",
    "fitness",
    "gym_bodybuilding",
    "yoga",
    "running",
    "martial_arts",
    "esports",

    // Technology
    "technology",
    "programming",
    "artificial_intelligence",
    "gadgets",
    "gaming",
    "cybersecurity",
    "web_development",
    "mobile_apps",
    "blockchain",

    // Lifestyle
    "fashion",
    "beauty",
    "skincare",
    "food_cooking",
    "travel",
    "photography",
    "home_decor",
    "parenting",
    "relationships",
    "self_improvement",
    "productivity",
    "minimalism",

    // Education & Knowledge
    "education",
    "science",
    "history",
    "psychology",
    "philosophy",
    "languages",
    "books_literature",
    "news_current_affairs",
    "politics",

    // Health
    "health",
    "mental_health",
    "nutrition",
    "medicine",
    "alternative_medicine",

    // Arts & Creativity
    "art_design",
    "writing",
    "photography_art",
    "crafts_diy",
    "film_making",

    // Nature & Animals
    "nature",
    "animals_pets",
    "environment",
    "gardening",

    // Automotive
    "automotive",
    "motorcycles",

    // Misc
    "comedy_memes",
    "astrology",
    "volunteering_charity",
    "career_jobs",
] as const;

export const hobbies = [
  // Creative & Arts
  "drawing",
  "painting",
  "sketching",
  "calligraphy",
  "photography",
  "videography",
  "graphic_design",
  "creative_writing",
  "poetry",
  "blogging",
  "journaling",
  "sculpting",
  "pottery",
  "origami",
  "coloring",

  // Music & Performance
  "playing_guitar",
  "playing_piano",
  "singing",
  "songwriting",
  "djing",
  "dancing",
  "acting",
  "stand_up_comedy",
  "beatboxing",

  // Crafts & DIY
  "knitting",
  "crocheting",
  "sewing",
  "embroidery",
  "woodworking",
  "candle_making",
  "soap_making",
  "jewelry_making",
  "scrapbooking",
  "upcycling",
  "model_building",
  "3d_printing",

  // Outdoor & Adventure
  "hiking",
  "camping",
  "fishing",
  "hunting",
  "cycling",
  "mountain_biking",
  "rock_climbing",
  "kayaking",
  "surfing",
  "swimming",
  "skateboarding",
  "skiing",
  "snowboarding",
  "birdwatching",
  "stargazing",
  "gardening",
  "foraging",

  // Sports & Fitness
  "running",
  "yoga",
  "gym_workout",
  "martial_arts",
  "boxing",
  "football_soccer",
  "basketball",
  "cricket",
  "tennis",
  "badminton",
  "table_tennis",
  "golf",
  "archery",
  "horseback_riding",

  // Games & Puzzles
  "video_gaming",
  "board_games",
  "chess",
  "card_games",
  "puzzles",
  "trivia_quizzes",
  "role_playing_games",
  "esports",

  // Food & Drink
  "cooking",
  "baking",
  "grilling_bbq",
  "coffee_brewing",
  "mixology",
  "wine_tasting",
  "food_blogging",

  // Collecting
  "collecting_stamps",
  "collecting_coins",
  "collecting_vintage_items",
  "collecting_sneakers",
  "collecting_action_figures",
  "collecting_books",

  // Learning & Mind
  "reading",
  "learning_languages",
  "meditation",
  "astrology",
  "philosophy_discussions",
  "quran_recitation",
  "islamic_studies",
  "history_exploring",
  "coding_programming",
  "robotics",
  "investing_stock_trading",

  // Home & Lifestyle
  "interior_decorating",
  "home_organizing",
  "diy_home_improvement",
  "pet_care",
  "car_detailing",
  "fashion_styling",
  "makeup_artistry",

  // Travel & Social
  "traveling",
  "road_trips",
  "volunteering",
  "networking_events",
  "podcasting",
  "vlogging",
] as const;

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
] as const;