CREATE TABLE IF NOT EXISTS User (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) not null unique,
    nationality VARCHAR(255) NOT NULL,
    languages JSON not null,
    age int not null,
    gender ENUM('male', 'female', 'other'),
    religion VARCHAR(255),
    bio VARCHAR(120),
    avatar VARCHAR(255),
    coverImage VARCHAR(255),
    education JSON,
    living_Address JSON,
    current_location JSON,
    current_job JSON,
    hobbies JSON not null,
    interest JSON not null,
    hashed_password VARCHAR(255) not null,
    salt VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT 1,
    is_verified BOOLEAN DEFAULT 0
);