CREATE TABLE `usersTable` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(255) NOT NULL,
	`age` int NOT NULL,
	`gender` varchar(255) NOT NULL,
	`nationality` varchar(50) NOT NULL,
	`is_verified` boolean DEFAULT false,
	`is_active` boolean DEFAULT true,
	`religion` varchar(100) NOT NULL,
	`bio` varchar(120),
	`avatar` varchar(255),
	`hashed_password` text NOT NULL,
	`salt` text NOT NULL,
	`languages` json,
	`hobbies` json,
	`interest` json,
	`location` json,
	`education` json,
	`job` json,
	CONSTRAINT `usersTable_id` PRIMARY KEY(`id`),
	CONSTRAINT `usersTable_id_unique` UNIQUE(`id`),
	CONSTRAINT `usersTable_email_unique` UNIQUE(`email`)
);
